controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

frontend:
    path: '/{req}'
    defaults: { _controller: 'App\Controller\MainController::index'}
    requirements:
        req: "^((?!api).)*$"